name: Build and publish to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        shell: cmd
        run: gradlew.bat build publish
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/maven-repo'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
